
services:
  frontend:
    build:
      context: ./tfront
      dockerfile: dockerfile.frontend
    volumes:
      - frontend-build:/usr/src/app/dist

  backend:
    build:
      context: ./tback
      dockerfile: dockerfile.backend
    ports:
      - "2700:2700"
    environment:
      - MONGO_URL=mongodb://mongo:27017/tashan
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
      - frontend
    volumes:
      - frontend-build:/usr/src/backend/public
      - ./tback/public/uploads:/usr/src/backend/public/uploads

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - tashan-network

  redis:
    image: redis:alpine
    networks:
      - tashan-network

volumes:
  mongo-data:
  frontend-build:
  

networks:
  tashan-network:
    driver: bridge